### ISSUE TITLE
ci-skip github action marking builds as failed

### ISSUE THREAD

**Issue by adierkens** [intuit/proof#9]
The current `skip ci` github action marks the commit as `failed` when it skips a build -- we should find a better way to handle that so it doesn't mark commits as bad

**Comment by anandsoni11** [comment]
I think this is the problem : 
[skip ci] action fails with code 78. See the error ["##[error]Docker run failed with exit code 78"] in your commit failures. This used to be recognized as a neutral code and recently Github stopped treating it as that. See this : https://twitter.com/ethomson/status/1163899559279497217 . They will come up with a different strategy to detect neutral exits like [skip ci].
 
One work around is to skip-checks for that commit since you don't want to run ci anyway. See this : https://help.github.com/en/articles/about-status-checks#skipping-and-requesting-checks-for-individual-commits . Not very sure but this might help as a temporary fix.

**Comment by Kausam** [comment]
I want to work on this issue.

**Comment by adierkens** [comment]
:rocket: Issue was released in v0.0.11 :rocket:
